apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.links: |
    - url: 'https://github.com/{{.resource.spec.repository.owner}}/{{.resource.spec.repository.name}}/pull/{{.resource.status.id}}'
      title: Pull Request
      if: resource.kind == "PullRequest"
