apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: scmprovider-example
spec:
  dryBranch: master
  activeCommitStatuses:
    - key: app-healthy
  environments:
    - branch: environments/dev
    - branch: environments/test
    - branch: environments/prod
  repository:
    name: argocd-example-apps
    owner: crenshaw-dev
    scmProviderRef:
      name: scmprovider-example
